"""
Base mutator interface for Autopoiesis.
"""

from __future__ import annotations

import abc
from typing import Optional

from autopoiesis.core.chromosome import Chromosome, SourceType
from autopoiesis.core.hotspot import BottleneckProfile


class BaseMutator(abc.ABC):
    """Abstract base class for genetic code mutators."""

    @property
    @abc.abstractmethod
    def name(self) -> str:
        """Name of the mutation operator."""
        pass

    @property
    @abc.abstractmethod
    def target_source_type(self) -> SourceType:
        """Type of code generated by this mutator."""
        pass

    @abc.abstractmethod
    def can_mutate(self, bottleneck: BottleneckProfile) -> bool:
        """Evaluates whether this mutator can operate on the given bottleneck."""
        pass

    @abc.abstractmethod
    def mutate(
        self,
        parent_chromosome: Chromosome,
        bottleneck: BottleneckProfile,
        target_dir: Optional[str] = None,
        generation: Optional[int] = None,
        parent_id: Optional[str] = None,
    ) -> Optional[Chromosome]:
        """Generates a candidate mutation from the parent chromosome."""
        pass
